[package]
name = "rustfs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
store = { path = "../store" }
tracing-subscriber = { version = "0.3.18" }
time = { workspace = true, features = ["parsing", "formatting"] }
