[workspace]
resolver = "2"
members = ["rustfs", "s3-object-layer"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rustfs/rustfs"
rust-version = "1.75"
