[package]
name = "rustfs-zip"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
async-compression = { version = "0.4.0", features = [
    "tokio",
    "bzip2",
    "gzip",
    "zlib",
    "zstd",
    "xz",
] }
async_zip = { version = "0.0.17", features = ["tokio"] }
zip = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tokio-tar = { workspace = true }
xz2 = { version = "0.1", optional = true, features = ["static"] }


[lints]
workspace = true
